dist: bionic
language: csharp
dotnet: "2.2"
mono: none

env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
        - DOTNET_CLI_TELEMETRY_OPTOUT=1

    install:
        - dotnet restore

    script:
        - dotnet build
        - dotnet test
