dist: bionic
language: csharp
dotnet: "3.0"
mono: none

env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
        - DOTNET_CLI_TELEMETRY_OPTOUT=1

install:
    - dotnet restore

script:
    - dotnet build -f netstandard2.1 zxcvbn-cs/zxcvbn-cs.csproj 
    - dotnet build -f netcoreapp3.0 zxcvbn-test/zxcvbn-test.csproj
    - dotnet test 
